project:
  type: website
  output-dir: docs

website:
  title: "warmup-alex-kincer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Boogly Boo
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



