project:
  type: website
  output-dir: docs

website:
  title: "Alex Kincer's Website Warmup"
  site-path: "/warmup-alex-kincer/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: articles/index.qmd
        text: Articles
      - href: posts/index.qmd
        text: Blog

  sidebar:
    - id: Articles
      title: "Articles"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - text: "What is Resilience?"
          href:  articles/article_01.qmd
        - text: "The Days in the Life of a High School Junior during a Global Pandemic"
          href:  articles/article_02.qmd
        - text: "Major Website Enhancement"
          href:  articles/article_03.qmd
        - section: "Posts"
          href: posts/index.qmd
          contents: "posts/*/*.qmd"
          sort:
            - "date desc"



format:
  html:
    theme: cosmo
    mainfont: 1.5rem
    fontcolor: "#d63384"
    linkcolor: "#d63384"
    css: styles.css
    toc: true
    footnotes-hover: true

execute:
  freeze: true


